# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

soda_main_allback <- function(xx, yy, xnames, fixset, norm = FALSE, verbose = FALSE, gam = 0, minF0 = 3L, allow_empty = FALSE) {
    .Call(`_MTWAS_soda_main_allback`, xx, yy, xnames, fixset, norm, verbose, gam, minF0, allow_empty)
}

